// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BackController from "./back_controller"
application.register("back", BackController)

import HashtagController from "./hashtag_controller"
application.register("hashtag", HashtagController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)
