default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>

development:
  <<: *default
  database: tweeter_x_clone

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
  username: jerson
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: your_production_host
